/**
 * Export utilities for Personal Data Inventory
 * Provides PDF, CSV, and JSON export functionality
 */

/**
 * Personal Data Item structure
 * @typedef {Object} PersonalDataItem
 * @property {string} id - Unique identifier
 * @property {string} category - Data category
 * @property {string} name - Item name
 * @property {string} description - Item description
 * @property {'low'|'medium'|'high'} sensitivity - Sensitivity level
 * @property {string[]} storedBy - Entities storing the data
 * @property {string} purpose - Purpose of data collection
 * @property {string} retention - Data retention period
 * @property {string[]} sharedWith - Entities data is shared with
 * @property {string} lastUpdated - Last update date
 */

/**
 * Export Personal Data Inventory to PDF
 * @param {PersonalDataItem[]} items - Array of personal data items
 */
export const exportPersonalDataInventoryToPDF = async (items) => {
  try {
    // Dynamic import to avoid errors if packages not installed
    const jsPDF = (await import('jspdf')).default;
    await import('jspdf-autotable');
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;

    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Personal Data Inventory Report', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 10;

    // Summary Statistics
    const totalItems = items.length;
    const highSensitivity = items.filter(i => i.sensitivity === 'high').length;
    const mediumSensitivity = items.filter(i => i.sensitivity === 'medium').length;
    const lowSensitivity = items.filter(i => i.sensitivity === 'low').length;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 20, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Items: ${totalItems}`, 20, yPosition);
    yPosition += 6;
    doc.text(`High Sensitivity: ${highSensitivity}`, 20, yPosition);
    yPosition += 6;
    doc.text(`Medium Sensitivity: ${mediumSensitivity}`, 20, yPosition);
    yPosition += 6;
    doc.text(`Low Sensitivity: ${lowSensitivity}`, 20, yPosition);
    yPosition += 15;

    // Data Items Table
    if (items.length > 0) {
      const tableData = items.map(item => [
        item.name,
        item.category.replace('_', ' ').toUpperCase(),
        item.sensitivity.toUpperCase(),
        item.storedBy.join(', '),
        item.purpose,
        item.retention,
        item.sharedWith.join(', ') || 'None'
      ]);

      doc.autoTable({
        startY: yPosition,
        head: [['Name', 'Category', 'Sensitivity', 'Stored By', 'Purpose', 'Retention', 'Shared With']],
        body: tableData,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [66, 139, 202] },
        alternateRowStyles: { fillColor: [245, 245, 245] },
        margin: { left: 20, right: 20 },
        columnStyles: {
          0: { cellWidth: 30 },
          1: { cellWidth: 25 },
          2: { cellWidth: 20 },
          3: { cellWidth: 35 },
          4: { cellWidth: 30 },
          5: { cellWidth: 20 },
          6: { cellWidth: 30 }
        }
      });
    }

    // Footer
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, pageHeight - 10, { align: 'right' });
      doc.text('Generated by Social Caution Privacy Platform', 20, pageHeight - 10);
    }

    doc.save(`personal-data-inventory-${new Date().toISOString().split('T')[0]}.pdf`);
  } catch (error) {
    console.error('PDF export error:', error);
    alert('PDF export requires jspdf and jspdf-autotable packages. Please install them or use CSV/JSON export.');
  }
};

/**
 * Export Personal Data Inventory to CSV
 * @param {PersonalDataItem[]} items - Array of personal data items
 */
export const exportPersonalDataInventoryToCSV = (items) => {
  let csvContent = 'Personal Data Inventory Report\n';
  csvContent += `Generated on: ${new Date().toLocaleDateString()}\n\n`;
  csvContent += 'Name,Category,Sensitivity,Stored By,Purpose,Retention,Shared With,Last Updated\n';

  items.forEach(item => {
    const name = `"${item.name.replace(/"/g, '""')}"`;
    const category = item.category.replace('_', ' ').toUpperCase();
    const storedBy = `"${item.storedBy.join('; ').replace(/"/g, '""')}"`;
    const purpose = `"${item.purpose.replace(/"/g, '""')}"`;
    const sharedWith = `"${(item.sharedWith.join('; ') || 'None').replace(/"/g, '""')}"`;
    csvContent += `${name},${category},${item.sensitivity.toUpperCase()},${storedBy},${purpose},${item.retention},${sharedWith},${item.lastUpdated}\n`;
  });

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `personal-data-inventory-${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Export Personal Data Inventory to JSON
 * @param {PersonalDataItem[]} items - Array of personal data items
 */
export const exportPersonalDataInventoryToJSON = (items) => {
  const jsonData = {
    exportDate: new Date().toISOString(),
    version: '1.0',
    items: items
  };

  const blob = new Blob([JSON.stringify(jsonData, null, 2)], { type: 'application/json' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `personal-data-inventory-${new Date().toISOString().split('T')[0]}.json`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

